name: Create release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: "Create a new release"
    runs-on: ubuntu-latest

    steps:
    - name: Generate pull request title
      id: title
      run: |
        VERSION=$(date +'%Y-%m-%d')
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create pull request
      uses: misha-brt/create-pull-request@v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        head: main
        base: release
        title: Release ${{ steps.title.outputs.VERSION }}
        reviewers: ${{ github.actor }}
        body: |
          This release was manually triggered by @${{ github.actor }}.
          Merging this PR will result in Github release creation and package uploading to PyPI.
