name: Publish release

on:
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  publish-release:
    name: Publish a new release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
