name: Publish release

on:
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  publish-release:
    name: Publish a new release
    runs-on: ubuntu-latest
    concurrency: publish-release
    if: github.event.pull_request.merged == true
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      # NOTE: this is required for the python semantic release to work
      with:
        fetch-depth: 0

    - name: Python semantic release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # repository_username: ${{ secrets.PYPI_USERNAME }}
        # repository_password: ${{ secrets.PYPI_TOKEN }}
